services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000" 
    networks:
      - mern_network
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb
      - redis  # ensure Redis starts before backend

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"  
    networks:
      - mern_network

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:     
      - mern_network
    volumes:
      - mongo-data:/data/db  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mern_network
    volumes:
      - redis-data:/data

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local  # persist Redis data
